config/routes.rb
Rails.application.routes.draw do
  get 'sales', to: 'sales#new'
  get 'sales/done'
  post 'sales', to: 'sales#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
class Sale < ApplicationRecord
  validates :cod, uniqueness: true
  validates :detail, presence: true
  validates :category, inclusion: { in: %w(uno dos tres cuatro cinco)}
  validates :value, numericality: { only_integer: true, :greater_than_or_equal_to => 0 }
  validates :discount, :numericality => { only_integer: true, :greater_than_or_equal_to => 0, :less_than_or_equal_to => 40 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

  def new
    @sale = Sale.new
  end

  def create
    @sale = Sale.new(sale_params)
    @discount = @sale.value.to_i * (@sale.discount.to_f/100)
    @sale.total = @sale.value.to_i - @discount
    if @sale.tax == 0
      @sale.total = @sale.total.to_f * 1.19
    end
    @sale.save
    redirect_to sales_done_path
  end

  def done
    @sales = Sale.all
  end


  private
  def sale_params

    params.require(:sale).permit(:cod, :detail, :category, :value, :discount, :tax)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RegistroVentas2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sales/done.html.erb
<h1>El registro fue almacenado con éxito!</h1>
<table class="table table-bordered">
  <thead>
    <th>Codigo </th>
    <th>Detalle </th>
    <th>Categoria </th>
    <th>Valor </th>
    <th>Descuento % </th>
    <th>IVA </th>
    <th>Total </th>
  </thead>
  <% @sales.each do |sale|%>
  <tbody>
    <td> <%= sale.cod %> </td>
    <td> <%= sale.detail %> </td>
    <td> <%= sale.category %> </td>
    <td> <%= sale.value %> </td>
    <td> <%= sale.discount %> </td>
    <td> <%= sale.tax %> </td>
    <td> <%= sale.total %> </td>



  </tbody>
<% end %>
</table>
<%= link_to "Volver", sales_path, class: 'btn btn-primary' %>

app/views/sales/new.html.erb
<table class="table table-striped">
  <thead>
    <th>Codigo </th>
    <th>Detalle </th>
    <th>Categoria </th>
    <th>Valor </th>
    <th>Descuento % </th>
    <th>IVA </th>
  </thead>
  <%= form_with model: @sale, local: true do |s| %>
  <tbody>
  <td><%= s.number_field :cod%></td>

  <td><%= s.text_area :detail %></td>

  <td><%= s.text_field :category%></td>

  <td><%= s.number_field :value%></td>

  <td><%= s.number_field :discount%></td>

  <td><%= s.check_box :tax%></td>

  </tbody>
</table>
<%= s.submit "Enviar" %>
<% end %>